// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-inputs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase-client.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  const token = ctx.getToken();
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    throw new Error("Not authenticated");
  }
}
function jsonResult(obj) {
  return { content: [{ type: "text", text: JSON.stringify(obj, null, 2) }] };
}
function textResult(text) {
  return { content: [{ type: "text", text }] };
}

// src/lib/mcp/tools/list-inputs.ts
var list_inputs_default = defineTool({
  name: "list_inputs",
  title: "List inputs",
  description: "List sources from the library. Optional filters: type, is_favorite, category_id, limit.",
  inputSchema: {
    type: z.enum(["pdf", "url", "youtube", "text"]).optional(),
    is_favorite: z.boolean().optional(),
    category_id: z.string().optional(),
    limit: z.number().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (params, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("inputs").select("id, title, type, original_url, summary, category_id, is_favorite, created_at").order("created_at", { ascending: false }).limit(params.limit ?? 50);
    if (params.type) q = q.eq("type", params.type);
    if (params.is_favorite !== void 0) q = q.eq("is_favorite", params.is_favorite);
    if (params.category_id) q = q.eq("category_id", params.category_id);
    const { data, error } = await q;
    if (error) throw error;
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/get-input.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_input_default = defineTool2({
  name: "get_input",
  title: "Get input",
  description: "Get full details of a specific source by ID.",
  inputSchema: { id: z2.string() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("inputs").select("*").eq("id", id).single();
    if (error) throw error;
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/create-input.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
var create_input_default = defineTool3({
  name: "create_input",
  title: "Create input",
  description: "Add a new text, url or youtube source to the library.",
  inputSchema: {
    title: z3.string(),
    type: z3.enum(["text", "url", "youtube"]),
    raw_content: z3.string().optional(),
    original_url: z3.string().optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async (params, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("inputs").insert({
      user_id: ctx.getUserId(),
      title: params.title,
      type: params.type,
      raw_content: params.raw_content ?? null,
      original_url: params.original_url ?? null
    }).select().single();
    if (error) throw error;
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/delete-input.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
var delete_input_default = defineTool4({
  name: "delete_input",
  title: "Delete input",
  description: "Delete a source from the library by ID.",
  inputSchema: { id: z4.string() },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("inputs").delete().eq("id", id);
    if (error) throw error;
    return textResult("Deleted successfully");
  }
});

// src/lib/mcp/tools/list-posts.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^4.4.3";
var list_posts_default = defineTool5({
  name: "list_posts",
  title: "List generated posts",
  description: "List generated posts including labels (personal/empresa), per-label publication dates, and LinkedIn performance metrics. Each post includes a `metrics` array and aggregated `performance` object. Filters: status, is_favorite, source_newsletter_id, created_after (ISO), created_before (ISO), label (name, case-insensitive), limit.",
  inputSchema: {
    status: z5.enum(["draft", "final", "published"]).optional(),
    is_favorite: z5.boolean().optional(),
    source_newsletter_id: z5.string().optional(),
    created_after: z5.string().optional(),
    created_before: z5.string().optional(),
    label: z5.string().optional(),
    limit: z5.number().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (params, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("generated_posts").select("id, title, content, status, goal, tone, language, is_favorite, source_newsletter_id, source_newsletter_item_id, created_at, published_at").order("created_at", { ascending: false }).limit(params.limit ?? 50);
    if (params.status) q = q.eq("status", params.status);
    if (params.is_favorite !== void 0) q = q.eq("is_favorite", params.is_favorite);
    if (params.source_newsletter_id) q = q.eq("source_newsletter_id", params.source_newsletter_id);
    if (params.created_after) q = q.gte("created_at", params.created_after);
    if (params.created_before) q = q.lte("created_at", params.created_before);
    const { data, error } = await q;
    if (error) throw error;
    const posts = data ?? [];
    if (posts.length === 0) return jsonResult([]);
    const postIds = posts.map((p) => p.id);
    const [{ data: assignments }, { data: publications }, { data: metrics }] = await Promise.all([
      supabase.from("post_label_assignments").select("post_id, label_id, post_labels(id, name, color)").in("post_id", postIds),
      supabase.from("post_label_publications").select("post_id, label_id, published_at").in("post_id", postIds),
      supabase.from("linkedin_post_metrics").select("post_id, source, impressions, clicks, reactions, comments, shares, engagement_rate, posted_at, linkedin_url, imported_at").in("post_id", postIds)
    ]);
    const pubMap = /* @__PURE__ */ new Map();
    for (const p of publications ?? []) pubMap.set(`${p.post_id}|${p.label_id}`, p.published_at);
    const labelsByPost = /* @__PURE__ */ new Map();
    for (const a of assignments ?? []) {
      const lbl = a.post_labels;
      if (!lbl) continue;
      const arr = labelsByPost.get(a.post_id) ?? [];
      arr.push({ id: lbl.id, name: lbl.name, color: lbl.color, published_at: pubMap.get(`${a.post_id}|${lbl.id}`) ?? null });
      labelsByPost.set(a.post_id, arr);
    }
    const metricsByPost = /* @__PURE__ */ new Map();
    for (const m of metrics ?? []) {
      if (!m.post_id) continue;
      const arr = metricsByPost.get(m.post_id) ?? [];
      const clicks = m.clicks || 0;
      const reactions = m.reactions || 0;
      const comments = m.comments || 0;
      const shares = m.shares || 0;
      const engagements = clicks + reactions + comments + shares;
      const existing = arr.find((x) => x.source === m.source);
      const row = { source: m.source, impressions: m.impressions || 0, clicks, reactions, comments, shares, engagements, engagement_rate: m.engagement_rate || 0, posted_at: m.posted_at, linkedin_url: m.linkedin_url, imported_at: m.imported_at };
      if (!existing) arr.push(row);
      else if (row.impressions > existing.impressions) Object.assign(existing, row);
      metricsByPost.set(m.post_id, arr);
    }
    const performanceByPost = /* @__PURE__ */ new Map();
    for (const [pid, rows] of metricsByPost.entries()) {
      const totals = rows.reduce((acc, r) => {
        acc.impressions += r.impressions;
        acc.clicks += r.clicks;
        acc.reactions += r.reactions;
        acc.comments += r.comments;
        acc.shares += r.shares;
        acc.engagements += r.engagements;
        return acc;
      }, { impressions: 0, clicks: 0, reactions: 0, comments: 0, shares: 0, engagements: 0 });
      const engagement_rate = totals.impressions > 0 ? totals.engagements / totals.impressions : 0;
      performanceByPost.set(pid, { ...totals, engagement_rate });
    }
    let enriched = posts.map((p) => ({
      ...p,
      labels: labelsByPost.get(p.id) ?? [],
      metrics: metricsByPost.get(p.id) ?? [],
      performance: performanceByPost.get(p.id) ?? null
    }));
    if (params.label && typeof params.label === "string") {
      const needle = params.label.toLowerCase();
      enriched = enriched.filter((p) => p.labels.some((l) => (l.name ?? "").toLowerCase() === needle));
    }
    return jsonResult(enriched);
  }
});

// src/lib/mcp/tools/get-post.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z6 } from "npm:zod@^4.4.3";
var get_post_default = defineTool6({
  name: "get_post",
  title: "Get post",
  description: "Get full details of a generated post by ID, including labels, per-label publication info, and aggregated LinkedIn performance metrics.",
  inputSchema: { id: z6.string() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("generated_posts").select("*").eq("id", id).single();
    if (error) throw error;
    const [{ data: assignments }, { data: publications }, { data: metrics }] = await Promise.all([
      supabase.from("post_label_assignments").select("label_id, post_labels(id, name, color)").eq("post_id", id),
      supabase.from("post_label_publications").select("label_id, published_at").eq("post_id", id),
      supabase.from("linkedin_post_metrics").select("source, impressions, engagement_rate, posted_at, linkedin_url, imported_at").eq("post_id", id)
    ]);
    const pubMap = /* @__PURE__ */ new Map();
    for (const p of publications ?? []) pubMap.set(p.label_id, p.published_at);
    const labels = (assignments ?? []).map((a) => a.post_labels).filter(Boolean).map((lbl) => ({ id: lbl.id, name: lbl.name, color: lbl.color, published_at: pubMap.get(lbl.id) ?? null }));
    const metricsAgg = [];
    for (const m of metrics ?? []) {
      const engagements = Math.round((m.impressions || 0) * (m.engagement_rate || 0));
      const row = { source: m.source, impressions: m.impressions || 0, engagements, engagement_rate: m.engagement_rate || 0, posted_at: m.posted_at, linkedin_url: m.linkedin_url, imported_at: m.imported_at };
      const existing = metricsAgg.find((x) => x.source === m.source);
      if (!existing) metricsAgg.push(row);
      else if (row.impressions > existing.impressions) Object.assign(existing, row);
    }
    return jsonResult({ ...data, labels, metrics: metricsAgg });
  }
});

// src/lib/mcp/tools/generate-post.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z7 } from "npm:zod@^4.4.3";

// src/lib/mcp/focus-angles.ts
var ES = {
  business: `\xC1NGULO: Impacto de negocio (perfiles comerciales y directivos)
- El lector decide sobre su empresa: comprar, invertir, priorizar. No busca contexto de mercado.
- Prioriza casos reales con n\xFAmeros. Usa SOLO cifras presentes en la fuente; si no hay cifras, formula el impacto de forma cualitativa y no inventes datos.
- Traduce tendencias t\xE9cnicas a decisiones de negocio (presupuesto, riesgo, plazos).
- Habla de errores caros: por qu\xE9 fallan los proyectos de anal\xEDtica/IA y cu\xE1nto cuesta.
- Aporta frameworks de decisi\xF3n: c\xF3mo saber si necesitas un dashboard, un agente, o nada.
- Opina con criterio de consultor: qu\xE9 compran las empresas y qu\xE9 acaba en un caj\xF3n.
- Evita la jerga t\xE9cnica; si aparece un t\xE9rmino, expl\xEDcalo en una l\xEDnea con su implicaci\xF3n econ\xF3mica.`,
  technical: `\xC1NGULO: Profundidad t\xE9cnica (perfiles t\xE9cnicos)
- Explica c\xF3mo funciona por dentro: arquitectura, flujo de datos, componentes clave.
- Da n\xFAmeros t\xE9cnicos presentes en la fuente: latencias, costes de c\xF3mputo, contexto, precisi\xF3n, l\xEDmites. No inventes cifras.
- Exp\xF3n trade-offs reales frente a la alternativa obvia.
- Incluye detalles de implementaci\xF3n que ahorran horas: configuraci\xF3n, patr\xF3n concreto, gotcha t\xEDpico.
- Opini\xF3n t\xE9cnica fundamentada: cu\xE1ndo esta soluci\xF3n no merece la pena.
- Usa el t\xE9rmino correcto sin diluirlo; asume que el lector conoce el dominio.`,
  strategic: `\xC1NGULO: Visi\xF3n de mercado y tendencia (direcci\xF3n, decisores)
- El lector quiere entender el mercado, no tomar una decisi\xF3n inmediata.
- Se\xF1ala qu\xE9 cambia en el sector y por qu\xE9 ahora: la se\xF1al concreta detr\xE1s de la noticia.
- Analiza movimientos de los actores relevantes y qu\xE9 implican para el resto.
- Plantea escenarios a 12-24 meses con su consecuencia pr\xE1ctica, e indica expl\xEDcitamente qu\xE9 se\xF1al invalidar\xEDa la predicci\xF3n.
- Di qu\xE9 apuestas envejecen mal y cu\xE1les ganan tracci\xF3n.
- Aporta una lectura propia del mercado, no un resumen neutro de la fuente.`,
  practical: `\xC1NGULO: Accionable (cualquier perfil que quiera aplicarlo)
- Di qu\xE9 puede hacer el lector hoy con esto: pasos concretos y ordenados.
- Indica requisitos previos reales (herramientas, datos, tiempo estimado).
- Incluye un ejemplo aplicado condensado, de 3 a 5 pasos m\xE1ximo, no gen\xE9rico.
- Menciona los errores frecuentes al intentarlo y c\xF3mo evitarlos.
- Cierra con un criterio de "hecho": c\xF3mo saber si ha funcionado.`,
  educational: `\xC1NGULO: Divulgativo (audiencia no experta)
- Explica el concepto desde cero con una analog\xEDa cotidiana.
- Deja claro por qu\xE9 importa a alguien que no trabaja en esto.
- Desmonta un malentendido habitual sobre el tema.
- Usa un ejemplo m\xEDnimo y reconocible.
- Cero jerga sin explicar.`,
  auto: `\xC1NGULO: elige t\xFA el m\xE1s adecuado seg\xFAn la fuente entre business (decisi\xF3n de empresa), strategic (lectura de mercado), practical (accionable), educational (divulgativo) y technical (profundidad t\xE9cnica).
En caso de duda entre dos \xE1ngulos, prioriza en este orden: business > strategic > practical > educational > technical.`
};
var EN = {
  business: `ANGLE: Business impact (commercial and executive profiles)
- The reader is deciding for their company: buy, invest, prioritise. They are not after market context.
- Prioritise real cases with numbers. Use ONLY figures present in the source; if there are none, express impact qualitatively and never invent data.
- Translate technical trends into business decisions (budget, risk, timelines).
- Cover expensive mistakes: why analytics/AI projects fail and what that costs.
- Offer decision frameworks: how to tell whether you need a dashboard, an agent, or nothing.
- Give a consultant's opinion: what companies actually buy and what ends up shelved.
- Avoid technical jargon; if a term appears, explain it in one line with its economic implication.`,
  technical: `ANGLE: Technical depth (technical profiles)
- Explain how it works under the hood: architecture, data flow, key components.
- Give technical numbers present in the source: latency, compute cost, context size, accuracy, limits. Never invent figures.
- Lay out real trade-offs against the obvious alternative.
- Include implementation details that save hours: configuration, a concrete pattern, a typical gotcha.
- Give a grounded technical opinion: when this solution is not worth it.
- Use the correct term without watering it down; assume domain knowledge.`,
  strategic: `ANGLE: Market view and trend (leadership, decision-makers)
- The reader wants to understand the market, not make an immediate decision.
- Point out what is changing in the sector and why now: the concrete signal behind the news.
- Analyse the moves of relevant players and what they imply for everyone else.
- Lay out 12-24 month scenarios with practical consequences, and explicitly state which signal would invalidate the prediction.
- Say which bets age badly and which gain traction.
- Provide your own reading of the market, not a neutral summary of the source.`,
  practical: `ANGLE: Actionable (anyone who wants to apply it)
- Say what the reader can do today: concrete, ordered steps.
- State real prerequisites (tools, data, estimated time).
- Include one condensed applied example, 3 to 5 steps maximum, not generic.
- Mention common mistakes and how to avoid them.
- Close with a "done" criterion: how to know it worked.`,
  educational: `ANGLE: Explanatory (non-expert audience)
- Explain the concept from scratch with an everyday analogy.
- Make clear why it matters to someone outside the field.
- Debunk a common misconception about the topic.
- Use a minimal, recognisable example.
- Zero unexplained jargon.`,
  auto: `ANGLE: choose the most suitable one for the source among business (company decision), strategic (market reading), practical (actionable), educational (explanatory) and technical (technical depth).
When torn between two angles, prefer this order: business > strategic > practical > educational > technical.`
};
var PT = {
  business: `\xC2NGULO: Impacto de neg\xF3cio (perfis comerciais e diretivos)
- O leitor decide sobre a sua empresa: comprar, investir, priorizar. N\xE3o procura contexto de mercado.
- Prioriza casos reais com n\xFAmeros. Usa APENAS valores presentes na fonte; se n\xE3o houver, formula o impacto de forma qualitativa e n\xE3o inventes dados.
- Traduz tend\xEAncias t\xE9cnicas em decis\xF5es de neg\xF3cio (or\xE7amento, risco, prazos).
- Fala de erros caros: porque falham os projetos de anal\xEDtica/IA e quanto custam.
- Oferece frameworks de decis\xE3o: como saber se precisas de um dashboard, de um agente, ou de nada.
- Opini\xE3o de consultor: o que as empresas compram e o que acaba na gaveta.
- Evita jarg\xE3o t\xE9cnico; se aparecer um termo, explica-o numa linha com a sua implica\xE7\xE3o econ\xF3mica.`,
  technical: `\xC2NGULO: Profundidade t\xE9cnica (perfis t\xE9cnicos)
- Explica como funciona por dentro: arquitetura, fluxo de dados, componentes-chave.
- D\xE1 n\xFAmeros t\xE9cnicos presentes na fonte: lat\xEAncias, custos de computa\xE7\xE3o, contexto, precis\xE3o, limites. N\xE3o inventes valores.
- Apresenta trade-offs reais face \xE0 alternativa \xF3bvia.
- Inclui detalhes de implementa\xE7\xE3o que poupam horas: configura\xE7\xE3o, padr\xE3o concreto, gotcha t\xEDpico.
- Opini\xE3o t\xE9cnica fundamentada: quando esta solu\xE7\xE3o n\xE3o compensa.
- Usa o termo correto sem o diluir; assume que o leitor conhece o dom\xEDnio.`,
  strategic: `\xC2NGULO: Vis\xE3o de mercado e tend\xEAncia (dire\xE7\xE3o, decisores)
- O leitor quer entender o mercado, n\xE3o tomar uma decis\xE3o imediata.
- Aponta o que muda no setor e porqu\xEA agora: o sinal concreto por tr\xE1s da not\xEDcia.
- Analisa os movimentos dos atores relevantes e o que implicam para os restantes.
- Prop\xF5e cen\xE1rios a 12-24 meses com consequ\xEAncia pr\xE1tica e indica explicitamente que sinal invalidaria a previs\xE3o.
- Diz que apostas envelhecem mal e quais ganham tra\xE7\xE3o.
- Traz uma leitura pr\xF3pria do mercado, n\xE3o um resumo neutro da fonte.`,
  practical: `\xC2NGULO: Acion\xE1vel (qualquer perfil que queira aplic\xE1-lo)
- Diz o que o leitor pode fazer hoje: passos concretos e ordenados.
- Indica requisitos pr\xE9vios reais (ferramentas, dados, tempo estimado).
- Inclui um exemplo aplicado condensado, de 3 a 5 passos no m\xE1ximo, n\xE3o gen\xE9rico.
- Menciona os erros frequentes e como evit\xE1-los.
- Fecha com um crit\xE9rio de "feito": como saber se funcionou.`,
  educational: `\xC2NGULO: Divulgativo (audi\xEAncia n\xE3o especialista)
- Explica o conceito de raiz com uma analogia do dia a dia.
- Deixa claro porque importa a quem n\xE3o trabalha nisto.
- Desmonta um mal-entendido habitual sobre o tema.
- Usa um exemplo m\xEDnimo e reconhec\xEDvel.
- Zero jarg\xE3o por explicar.`,
  auto: `\xC2NGULO: escolhe o mais adequado \xE0 fonte entre business (decis\xE3o de empresa), strategic (leitura de mercado), practical (acion\xE1vel), educational (divulgativo) e technical (profundidade t\xE9cnica).
Em caso de d\xFAvida entre dois \xE2ngulos, prioriza esta ordem: business > strategic > practical > educational > technical.`
};
var BY_LANG = { es: ES, en: EN, pt: PT };
function focusAngleInstruction(angle, language) {
  if (!angle) return null;
  const lang = language === "en" ? "en" : language === "pt" ? "pt" : "es";
  return BY_LANG[lang][angle] ?? null;
}

// src/lib/mcp/generate-content.ts
var goalMap = { educate: "Educar a la audiencia", inspire: "Inspirar y motivar", promote: "Promocionar un producto o servicio", engage: "Generar engagement y conversaci\xF3n", storytelling: "Contar una historia" };
var toneMap = { professional: "profesional", casual: "casual y cercano", inspirational: "inspiracional", direct: "directo y conciso", humorous: "con humor" };
var lengthMap = { short: "corto (~100 palabras)", medium: "medio (~200 palabras)", long: "largo (~300 palabras)" };
var ctaMap = { question: "una pregunta abierta al lector", share: "invitar a compartir", follow: "invitar a seguir", link: "invitar a visitar un enlace", none: "sin call to action" };
var langMap = { es: "espa\xF1ol", en: "ingl\xE9s", pt: "portugu\xE9s" };
async function generateContent(supabase, params) {
  let sourceTexts = [];
  if (params.input_ids?.length) {
    const { data: inputs } = await supabase.from("inputs").select("title, raw_content, extracted_content, summary, original_url, type").in("id", params.input_ids);
    sourceTexts = (inputs || []).map((inp) => {
      const content = inp.extracted_content || inp.raw_content || inp.summary || "";
      return `[${inp.type.toUpperCase()}] ${inp.title}
${content}${inp.original_url ? `
URL: ${inp.original_url}` : ""}`;
    });
  }
  let voiceTexts = [];
  if (params.voice_id) {
    const { data: samples } = await supabase.from("voice_samples").select("title, content").eq("voice_id", params.voice_id).limit(10);
    if (samples?.length) voiceTexts = samples.map((s) => `${s.title ? `[${s.title}] ` : ""}${s.content}`);
  }
  let systemPrompt = `Eres un experto creador de contenido para LinkedIn.
Generas posts de alta calidad, optimizados para engagement.
Usa emojis con moderaci\xF3n, formato con saltos de l\xEDnea y estructura visual clara.
NO uses markdown (ni asteriscos ni negritas), escribe en texto plano.
IMPORTANTE: NO empieces el post con texto entre corchetes.`;
  if (voiceTexts.length > 0) {
    systemPrompt += `

ESTILO DE ESCRITURA - Imita este estilo:
${voiceTexts.map((t, i) => `--- Ejemplo ${i + 1} ---
${t}`).join("\n\n")}
--- Fin ---`;
  }
  let userPrompt = "Genera un post para LinkedIn";
  if (sourceTexts.length > 0) userPrompt += ` bas\xE1ndote en:

${sourceTexts.join("\n\n---\n\n")}`;
  const specs = [];
  if (params.goal && goalMap[params.goal]) specs.push(`Objetivo: ${goalMap[params.goal]}`);
  if (params.tone && toneMap[params.tone]) specs.push(`Tono: ${toneMap[params.tone]}`);
  if (params.language && langMap[params.language]) specs.push(`Idioma: ${langMap[params.language]}`);
  if (params.length && lengthMap[params.length]) specs.push(`Longitud: ${lengthMap[params.length]}`);
  if (params.cta && ctaMap[params.cta]) specs.push(`CTA: ${ctaMap[params.cta]}`);
  if (params.target_audience) specs.push(`Audiencia objetivo: ${params.target_audience}`);
  if (specs.length) userPrompt += `

Especificaciones:
${specs.join("\n")}`;
  const angleBlock = focusAngleInstruction(params.focus_angle, params.language);
  if (angleBlock) userPrompt += `

${angleBlock}`;
  if (params.content_focus) userPrompt += `

ENFOQUE:
${params.content_focus}`;
  userPrompt += "\n\nDevuelve solo el post, sin explicaciones ni metadatos.";
  const LOVABLE_API_KEY = process.env.LOVABLE_API_KEY;
  if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");
  const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: { Authorization: `Bearer ${LOVABLE_API_KEY}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      model: "google/gemini-3-flash-preview",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ]
    })
  });
  if (!aiResponse.ok) {
    const e = await aiResponse.text();
    throw new Error(`AI error ${aiResponse.status}: ${e}`);
  }
  const aiResult = await aiResponse.json();
  return (aiResult.choices?.[0]?.message?.content || "").replace(/^\s*\[.*?\]\s*/g, "");
}

// src/lib/mcp/tools/generate-post.ts
var generate_post_default = defineTool7({
  name: "generate_post",
  title: "Generate LinkedIn post",
  description: "Generate a LinkedIn post from selected sources. If save=true, also persists it to the database in one call.",
  inputSchema: {
    input_ids: z7.array(z7.string()).optional(),
    goal: z7.enum(["educate", "inspire", "promote", "engage", "storytelling"]).optional(),
    tone: z7.enum(["professional", "casual", "inspirational", "direct", "humorous"]).optional(),
    language: z7.enum(["es", "en", "pt"]).optional(),
    length: z7.enum(["short", "medium", "long"]).optional(),
    cta: z7.enum(["question", "share", "follow", "link", "none"]).optional(),
    target_audience: z7.string().optional(),
    content_focus: z7.string().optional(),
    voice_id: z7.string().optional(),
    save: z7.boolean().optional(),
    status: z7.enum(["draft", "final", "published"]).optional(),
    title: z7.string().optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: true },
  handler: async (params, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const content = await generateContent(supabase, params);
    if (!params.save) return textResult(content);
    const { data, error } = await supabase.from("generated_posts").insert({
      user_id: ctx.getUserId(),
      content,
      title: params.title ?? null,
      input_id: params.input_ids?.[0] ?? null,
      input_ids: params.input_ids ?? [],
      goal: params.goal ?? null,
      tone: params.tone ?? null,
      language: params.language ?? null,
      length: params.length ?? null,
      cta: params.cta ?? null,
      target_audience: params.target_audience ?? null,
      content_focus: params.content_focus ?? null,
      voice_id: params.voice_id ?? null,
      status: params.status ?? "draft"
    }).select().single();
    if (error) throw error;
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/save-post.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z8 } from "npm:zod@^4.4.3";
var save_post_default = defineTool8({
  name: "save_post",
  title: "Save post",
  description: "Save a previously generated post to the database.",
  inputSchema: {
    content: z8.string(),
    title: z8.string().optional(),
    input_ids: z8.array(z8.string()).optional(),
    goal: z8.string().optional(),
    tone: z8.string().optional(),
    language: z8.string().optional(),
    length: z8.string().optional(),
    cta: z8.string().optional(),
    target_audience: z8.string().optional(),
    content_focus: z8.string().optional(),
    voice_id: z8.string().optional(),
    status: z8.enum(["draft", "final", "published"]).optional(),
    source_newsletter_id: z8.string().optional(),
    source_newsletter_item_id: z8.string().optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async (params, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("generated_posts").insert({
      user_id: ctx.getUserId(),
      content: params.content,
      title: params.title ?? null,
      input_id: params.input_ids?.[0] ?? null,
      input_ids: params.input_ids ?? [],
      goal: params.goal ?? null,
      tone: params.tone ?? null,
      language: params.language ?? null,
      length: params.length ?? null,
      cta: params.cta ?? null,
      target_audience: params.target_audience ?? null,
      content_focus: params.content_focus ?? null,
      voice_id: params.voice_id ?? null,
      status: params.status ?? "draft",
      source_newsletter_id: params.source_newsletter_id ?? null,
      source_newsletter_item_id: params.source_newsletter_item_id ?? null
    }).select().single();
    if (error) throw error;
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/update-post.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z9 } from "npm:zod@^4.4.3";
var update_post_default = defineTool9({
  name: "update_post",
  title: "Update post",
  description: "Update an existing post by ID.",
  inputSchema: {
    id: z9.string(),
    content: z9.string().optional(),
    title: z9.string().optional(),
    status: z9.enum(["draft", "final", "published"]).optional(),
    goal: z9.string().optional(),
    tone: z9.string().optional(),
    language: z9.string().optional(),
    length: z9.string().optional(),
    cta: z9.string().optional(),
    target_audience: z9.string().optional(),
    content_focus: z9.string().optional(),
    voice_id: z9.string().optional(),
    is_favorite: z9.boolean().optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (params, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { id, ...updates } = params;
    const cleanUpdates = {};
    for (const [k, v] of Object.entries(updates)) if (v !== void 0) cleanUpdates[k] = v;
    if (Object.keys(cleanUpdates).length === 0) throw new Error("No fields to update");
    const { data, error } = await supabase.from("generated_posts").update(cleanUpdates).eq("id", id).select().single();
    if (error) throw error;
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/delete-post.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z10 } from "npm:zod@^4.4.3";
var delete_post_default = defineTool10({
  name: "delete_post",
  title: "Delete post",
  description: "Delete a generated post by ID.",
  inputSchema: { id: z10.string() },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("generated_posts").delete().eq("id", id);
    if (error) throw error;
    return textResult("Deleted successfully");
  }
});

// src/lib/mcp/tools/list-voices.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_voices_default = defineTool11({
  name: "list_voices",
  title: "List voices",
  description: "List available writing voice profiles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_params, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("voices").select("id, name, description, created_at").order("created_at", { ascending: false });
    if (error) throw error;
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/get-user-defaults.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_user_defaults_default = defineTool12({
  name: "get_user_defaults",
  title: "Get user defaults",
  description: "Get the user's profile defaults (default voice, CTA, length, languages, writing style, newsletter preferences).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_params, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("id, full_name, default_voice_id, default_cta, default_length, preferred_language, app_language, default_writing_style, newsletter_preferences").eq("id", ctx.getUserId()).single();
    if (error) throw error;
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-newsletters.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z11 } from "npm:zod@^4.4.3";
var list_newsletters_default = defineTool13({
  name: "list_newsletters",
  title: "List newsletters",
  description: "List generated newsletters. Optional limit (default 20).",
  inputSchema: { limit: z11.number().optional() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (params, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("newsletters").select("id, topic, language, created_at").order("created_at", { ascending: false }).limit(params.limit ?? 20);
    if (error) throw error;
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/get-newsletter.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z12 } from "npm:zod@^4.4.3";
var get_newsletter_default = defineTool14({
  name: "get_newsletter",
  title: "Get newsletter",
  description: "Get full newsletter content by ID, including its items.",
  inputSchema: { id: z12.string() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data: newsletter, error } = await supabase.from("newsletters").select("*").eq("id", id).single();
    if (error) throw error;
    const { data: items } = await supabase.from("newsletter_items").select("*").eq("newsletter_id", id).order("created_at");
    return jsonResult({ ...newsletter, items: items || [] });
  }
});

// src/lib/mcp/tools/list-newsletter-items.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z13 } from "npm:zod@^4.4.3";
var list_newsletter_items_default = defineTool15({
  name: "list_newsletter_items",
  title: "List newsletter items",
  description: "List items (sources found) for a given newsletter.",
  inputSchema: { newsletter_id: z13.string() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ newsletter_id }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("newsletter_items").select("id, title, url, description, source_type, imported_to_library, input_id, pub_date, created_at").eq("newsletter_id", newsletter_id).order("created_at");
    if (error) throw error;
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/generate-newsletter.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z14 } from "npm:zod@^4.4.3";
var generate_newsletter_default = defineTool16({
  name: "generate_newsletter",
  title: "Generate newsletter",
  description: "Generate a fresh newsletter using the user's preferences. Returns newsletter_id and items found.",
  inputSchema: {
    topic: z14.string().optional(),
    language: z14.enum(["es", "en", "pt"]).optional(),
    freshness_months: z14.number().optional(),
    preference_profile_id: z14.string().optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: true },
  handler: async (params, ctx) => {
    requireAuth(ctx);
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const ANON_KEY = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    const token = ctx.getToken();
    const resp = await fetch(`${SUPABASE_URL}/functions/v1/generate-newsletter`, {
      method: "POST",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", apikey: ANON_KEY },
      body: JSON.stringify(params)
    });
    if (!resp.ok) throw new Error(`generate-newsletter failed ${resp.status}: ${await resp.text()}`);
    return jsonResult(await resp.json());
  }
});

// src/lib/mcp/tools/import-newsletter-item.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z15 } from "npm:zod@^4.4.3";
var import_newsletter_item_default = defineTool17({
  name: "import_newsletter_item_as_input",
  title: "Import newsletter item",
  description: "Import a newsletter item into the library as a reusable input.",
  inputSchema: {
    item_id: z15.string(),
    extract_content: z15.boolean().optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: true },
  handler: async ({ item_id, extract_content }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data: item, error: ie } = await supabase.from("newsletter_items").select("*").eq("id", item_id).single();
    if (ie) throw ie;
    if (item.input_id) {
      const { data: existing } = await supabase.from("inputs").select("*").eq("id", item.input_id).single();
      return jsonResult({ input: existing, already_imported: true });
    }
    const isYoutube = (item.url || "").includes("youtube.com") || (item.url || "").includes("youtu.be");
    const type = isYoutube ? "youtube" : "url";
    let extracted = null;
    if (extract_content) {
      const SUPABASE_URL = process.env.SUPABASE_URL;
      const ANON_KEY = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
      try {
        const ex = await fetch(`${SUPABASE_URL}/functions/v1/extract-url`, {
          method: "POST",
          headers: { Authorization: `Bearer ${ctx.getToken()}`, "Content-Type": "application/json", apikey: ANON_KEY },
          body: JSON.stringify({ url: item.url })
        });
        if (ex.ok) {
          const d = await ex.json();
          extracted = d.content || d.extracted_content || null;
        }
      } catch {
      }
    }
    const { data: input, error: ce } = await supabase.from("inputs").insert({
      user_id: ctx.getUserId(),
      title: item.title,
      type,
      original_url: item.url,
      raw_content: extracted,
      summary: item.description || null
    }).select().single();
    if (ce) throw ce;
    await supabase.from("newsletter_items").update({ imported_to_library: true, input_id: input.id }).eq("id", item_id);
    return jsonResult({ input, already_imported: false });
  }
});

// src/lib/mcp/tools/generate-posts-from-newsletter.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z16 } from "npm:zod@^4.4.3";
var generate_posts_from_newsletter_default = defineTool18({
  name: "generate_posts_from_newsletter",
  title: "Generate posts from newsletter",
  description: "Atomic daily-agent action: import all items from a newsletter, generate 1 draft post per item, and return the created posts. Idempotent per (user, newsletter_item).",
  inputSchema: {
    newsletter_id: z16.string(),
    voice_id: z16.string().optional(),
    goal: z16.string().optional(),
    tone: z16.string().optional(),
    language: z16.string().optional(),
    length: z16.string().optional(),
    cta: z16.string().optional(),
    target_audience: z16.string().optional(),
    content_focus: z16.string().optional(),
    extract_content: z16.boolean().optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: true },
  handler: async (params, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const ANON_KEY = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    const { data: items, error } = await supabase.from("newsletter_items").select("*").eq("newsletter_id", params.newsletter_id);
    if (error) throw error;
    if (!items?.length) return jsonResult({ posts: [], skipped: 0, message: "No items in newsletter" });
    const results = [];
    let skipped = 0;
    for (const item of items) {
      const { data: existing } = await supabase.from("generated_posts").select("id").eq("user_id", userId).eq("source_newsletter_item_id", item.id).maybeSingle();
      if (existing) {
        skipped++;
        continue;
      }
      let inputId = item.input_id;
      if (!inputId) {
        const isYoutube = (item.url || "").includes("youtube.com") || (item.url || "").includes("youtu.be");
        let extracted = null;
        if (params.extract_content) {
          try {
            const ex = await fetch(`${SUPABASE_URL}/functions/v1/extract-url`, {
              method: "POST",
              headers: { Authorization: `Bearer ${ctx.getToken()}`, "Content-Type": "application/json", apikey: ANON_KEY },
              body: JSON.stringify({ url: item.url })
            });
            if (ex.ok) {
              const d = await ex.json();
              extracted = d.content || d.extracted_content || null;
            }
          } catch {
          }
        }
        const { data: newInput, error: ie } = await supabase.from("inputs").insert({
          user_id: userId,
          title: item.title,
          type: isYoutube ? "youtube" : "url",
          original_url: item.url,
          raw_content: extracted,
          summary: item.description || null
        }).select().single();
        if (ie) {
          results.push({ item_id: item.id, error: ie.message });
          continue;
        }
        inputId = newInput.id;
        await supabase.from("newsletter_items").update({ imported_to_library: true, input_id: inputId }).eq("id", item.id);
      }
      try {
        const content = await generateContent(supabase, { ...params, input_ids: [inputId] });
        const { data: post, error: pe } = await supabase.from("generated_posts").insert({
          user_id: userId,
          content,
          title: item.title,
          input_id: inputId,
          input_ids: [inputId],
          goal: params.goal ?? null,
          tone: params.tone ?? null,
          language: params.language ?? null,
          length: params.length ?? null,
          cta: params.cta ?? null,
          target_audience: params.target_audience ?? null,
          content_focus: params.content_focus ?? null,
          voice_id: params.voice_id ?? null,
          status: "draft",
          source_newsletter_id: params.newsletter_id,
          source_newsletter_item_id: item.id
        }).select("id, title").single();
        if (pe) {
          results.push({ item_id: item.id, error: pe.message });
          continue;
        }
        results.push({ item_id: item.id, input_id: inputId, post_id: post.id, title: post.title });
      } catch (e) {
        results.push({ item_id: item.id, error: e.message });
      }
    }
    return jsonResult({ posts: results, skipped, total_items: items.length });
  }
});

// src/lib/mcp/tools/notify-review.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z17 } from "npm:zod@^4.4.3";
var notify_review_default = defineTool19({
  name: "notify_review",
  title: "Notify review",
  description: "Send a notification (email) summarizing posts ready for review. Includes deep links.",
  inputSchema: {
    post_ids: z17.array(z17.string()),
    subject: z17.string().optional(),
    summary: z17.string().optional(),
    to: z17.string().optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: true },
  handler: async (params, ctx) => {
    requireAuth(ctx);
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const ANON_KEY = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    const resp = await fetch(`${SUPABASE_URL}/functions/v1/notify-review`, {
      method: "POST",
      headers: { Authorization: `Bearer ${ctx.getToken()}`, "Content-Type": "application/json", apikey: ANON_KEY },
      body: JSON.stringify(params)
    });
    if (!resp.ok) throw new Error(`notify-review failed ${resp.status}: ${await resp.text()}`);
    return jsonResult(await resp.json());
  }
});

// src/lib/mcp/tools/log-agent-run.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z18 } from "npm:zod@^4.4.3";
var log_agent_run_default = defineTool20({
  name: "log_agent_run",
  title: "Log agent run",
  description: "Record the outcome of an agent execution for auditing and idempotency.",
  inputSchema: {
    newsletter_id: z18.string().optional(),
    posts_created: z18.number().optional(),
    status: z18.enum(["running", "success", "error", "partial"]).optional(),
    error: z18.string().optional(),
    notified: z18.boolean().optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async (params, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("agent_runs").insert({
      user_id: ctx.getUserId(),
      newsletter_id: params.newsletter_id ?? null,
      posts_created: params.posts_created ?? 0,
      status: params.status ?? "success",
      error: params.error ?? null,
      notified_at: params.notified ? (/* @__PURE__ */ new Date()).toISOString() : null,
      finished_at: (/* @__PURE__ */ new Date()).toISOString()
    }).select().single();
    if (error) throw error;
    return jsonResult(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "ofpnsqvcagowvaavzzxh";
var mcp_default = defineMcp({
  name: "postflow",
  title: "PostFlow",
  version: "1.0.0",
  instructions: "PostFlow tools to manage your LinkedIn content library, generate posts, curate newsletters, and log agent runs. Every tool acts on behalf of the signed-in user and respects row-level security. Use `list_inputs` / `list_posts` to discover state, `generate_post` (with `save: true`) to draft new posts, and `generate_posts_from_newsletter` for atomic newsletter-to-drafts runs.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_user_defaults_default,
    list_inputs_default,
    get_input_default,
    create_input_default,
    delete_input_default,
    list_posts_default,
    get_post_default,
    generate_post_default,
    save_post_default,
    update_post_default,
    delete_post_default,
    list_voices_default,
    list_newsletters_default,
    get_newsletter_default,
    list_newsletter_items_default,
    generate_newsletter_default,
    import_newsletter_item_default,
    generate_posts_from_newsletter_default,
    notify_review_default,
    log_agent_run_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
